---
- name: Uninstall existing packer package
  package:
    name: packer
    state: absent

- name: Download the package
  get_url:
    url: "https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip"
    dest: "{{ packer_zip_tmp }}"
    checksum: "sha256:{{ packer_package_checksum }}"
  register: response
  changed_when: "response.status_code != 200"

- name: Install unzip
  package:
    name: unzip
    state: present

- name: Unarchive
  unarchive:
    src: "{{ packer_zip_tmp }}"
    remote_src: yes
    dest: /usr/local/bin

- name: Clean
  file:
    name: "{{ packer_zip_tmp }}"
    state: absent
  register: result
  changed_when: "result.diff.before.state != 'file' or result.diff.after.state != 'absent'"
